# Generated by Django 2.0.5 on 2018-06-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0003_auto_20180530_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='IM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateField(auto_created=True, auto_now_add=True)),
                ('room', models.CharField(max_length=255, verbose_name='群id')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_im+', to='mycode.Game')),
                ('game_club', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_club_im+', to='mycode.GameClub')),
            ],
        ),
    ]
