# Generated by Django 2.0.5 on 2018-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0004_unreadmessage_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_club_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='总费用')),
                ('score', models.CharField(blank=True, max_length=255, verbose_name='比分')),
                ('award', models.CharField(blank=True, max_length=255, null=True, verbose_name='奖品')),
                ('success', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('game', models.ManyToManyField(related_name='_game_club_report_game_+', to='mycode.Game')),
                ('game_clubA', models.ManyToManyField(related_name='_game_club_report_game_clubA_+', to='mycode.GameClub')),
                ('game_clubB', models.ManyToManyField(related_name='_game_club_report_game_clubB_+', to='mycode.GameClub')),
                ('win_club', models.ManyToManyField(blank=True, null=True, related_name='_game_club_report_win_club_+', to='mycode.GameClub')),
            ],
        ),
        migrations.CreateModel(
            name='game_club_report_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateField(auto_created=True, auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(default='', max_length=255, verbose_name='图片介绍')),
                ('url', models.URLField(blank=True, null=True)),
                ('game_club', models.ManyToManyField(blank=True, related_name='_game_club_report_images_game_club_+', to='mycode.GameClub')),
                ('game_club_report', models.ManyToManyField(related_name='_game_club_report_images_game_club_report_+', to='mycode.Game_club_report')),
            ],
        ),
    ]
