# Generated by Django 2.0.5 on 2018-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0005_game_club_report_game_club_report_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadmessage',
            name='unread_game_club_report',
            field=models.ManyToManyField(blank=True, null=True, related_name='_unreadmessage_unread_game_club_report_+', to='mycode.Game_club_report'),
        ),
    ]
