# Generated by Django 2.0.5 on 2018-06-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0006_unreadmessage_unread_game_club_report'),
        ('mycode', '0004_im'),
    ]

    operations = [
    ]
