# Generated by Django 2.0.5 on 2018-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0007_merge_20180615_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_club_report_commond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('anonymity', models.IntegerField(default=10)),
                ('rank', models.IntegerField(default=10)),
                ('skillrank', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='game_club_report',
            name='temp_score',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预比分'),
        ),
        migrations.AddField(
            model_name='game_club_report_commond',
            name='game_club',
            field=models.ManyToManyField(blank=True, null=True, related_name='_game_club_report_commond_game_club_+', to='mycode.Game_club_report'),
        ),
        migrations.AddField(
            model_name='game_club_report_commond',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='_game_club_report_commond_user_+', to='mycode.Account'),
        ),
    ]
