# Generated by Django 2.0.5 on 2018-06-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0009_game_club_report_images_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_club_report_commond',
            name='game_club',
        ),
        migrations.AddField(
            model_name='game_club_report_commond',
            name='game_club_report',
            field=models.ManyToManyField(blank=True, null=True, related_name='_game_club_report_commond_game_club_report_+', to='mycode.Game_club_report'),
        ),
    ]
