# Generated by Django 2.0.5 on 2018-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0010_auto_20180620_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='account',
            name='game_age',
            field=models.IntegerField(default=0, null=True, verbose_name='球龄'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='account',
            name='good_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='擅长'),
        ),
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.IntegerField(default=0, null=True, verbose_name='身高CM'),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='account',
            name='province',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='所在省份'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sign',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.IntegerField(default=0, null=True, verbose_name='体重KG'),
        ),
    ]
