# Generated by Django 2.0.5 on 2018-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycode', '0011_auto_20180625_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(null=True)),
                ('order_title', models.CharField(default='充值', max_length=255)),
                ('order_desc', models.CharField(default='账户充值', max_length=255)),
                ('order_type', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('rate', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ManyToManyField(blank=True, null=True, related_name='Game', to='mycode.Game')),
                ('game_club', models.ManyToManyField(blank=True, null=True, related_name='game_club', to='mycode.GameClub')),
                ('game_report', models.ManyToManyField(blank=True, null=True, related_name='Game_club_report', to='mycode.Game_club_report')),
                ('user', models.ManyToManyField(related_name='order_create_user', to='mycode.Account')),
            ],
        ),
    ]
